"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

Notes:
    - if you get an error about missing 'libpython3.5.dylib', make a symlink
      to 'libpython3.5m.dylib'
"""

from setuptools import setup
import platform
from mesher import consts
from glob import glob

main_script = 'mesher/__main__.py'
assets_dir = 'mesher/assets'

if platform.system() == 'Darwin':
    PLIST_INFO = {
        'CFBundleName': consts.APP_NAME,
        'CFBundleDisplayName': consts.APP_NAME,
        'CFBundleGetInfoString': consts.DESCRIPTION,
        'CFBundleIdentifier': "name.andrs.osx.mesher",
        'CFBundleVersion': str(consts.VERSION),
        'CFBundleShortVersionString': str(consts.VERSION),
        'NSHumanReadableCopyright': consts.COPYRIGHT
    }

    extra_options = dict(
        setup_requires=['py2app'],
        app=[main_script],
        data_files=[
            ('icons', glob(assets_dir + '/icons/*.svg')),
            ('icons', glob(assets_dir + '/icons/*.png'))
        ],
        options={
            'py2app': {
                'argv_emulation': False,
                'plist': PLIST_INFO,
                'iconfile': 'icon.icns',
                'packages': [
                    'vtk', 'fcntl', 'pandas', 'cmath', 'glob'
                ]
            }
        }
    )
elif platform.system() == 'win32':
    extra_options = dict(
     setup_requires=['py2exe'],
     app=[main_script],
    )
else:
    extra_options = dict(
        # Normally unix-like platforms will use "setup.py install" and install
        # the main script as such
        scripts=[main_script]
    )

setup(
    name=consts.APP_NAME,
    version=consts.VERSION,
    author='David Andrš',
    author_email='andrsd@gmail.com',
    url='https://github.com/andrsd/mesher',
    license='LICENSE',
    description=consts.DESCRIPTION,
    install_requires=[
        'PyQt5==5.13.1',
        'PyQtChart==5.13.1',
        'sphinx',
        'vtk==9.0.3',
    ],
    packages=[
        'mesher',
    ],
    entry_points={
        'gui_scripts': [
            'mesher = mesher.__main__:main'
        ]
    },
    include_package_data=True,
    package_data={
        'mesher.assets': ['*.svg']
    },
    **extra_options
)
